name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout кода
      - name: Checkout code
        uses: actions/checkout@v3

      # Установка .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # Восстановление зависимостей
      - name: Restore dependencies
        run: dotnet restore hosts/onlinestore.mvc

      # Сборка проекта
      - name: Build project
        run: dotnet build hosts/onlinestore.mvc --configuration Release --no-restore

      # Сборка Docker-образа
      - name: Build Docker image
        run: docker build --build-arg BUILD_CONFIGURATION=Release -t myapp:latest ./hosts/onlinestore.mvc

      # Сохранение Docker-образа
      - name: Save Docker image
        run: docker save myapp:latest -o myapp.tar

      # Загрузка Docker-образа как артефакта
      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v2
        with:
          name: docker-image
          path: myapp.tar

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Скачивание Docker-образа
      - name: Download Docker image artifact
        uses: actions/download-artifact@v2
        with:
          name: docker-image
          path: ./

      # Копирование Docker-образа на сервер
      - name: Copy Docker image to remote server
        uses: appleboy/scp-action@v1.1.0
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: ./myapp.tar
          target: /home/youruser/

      # Деплой на сервере
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.1.7
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            # Загрузка Docker-образа
            docker load -i /home/youruser/myapp.tar
            # Остановка старого контейнера
            docker stop myapp || true
            docker rm myapp || true
            # Запуск нового контейнера
            docker run -d --name myapp -p 80:80 -e ConnectionStrings__DefaultConnection=${{ secrets.ConnectionStrings__DefaultConnection }} myapp:latest
